### ISSUE TITLE
declare observable of observable type

### ISSUE THREAD

**Issue by klokane** [victimsnino/ReactivePlusPlus#633]
Hi, firstly thank you for great library. 

My question is following: There is, in Rx, often used concept `observable<observable<type>>`.

`flat_map()` or `switch_on_next()` use them as input stream. Is there way how to declare it?

`dynamic_observable<dynamic_observable<int>>` complains because of "no appropriate default constructor"

I know, I can use `subject<dynamic_observer<type>>` and access it via `get_observable()`. But direct way for "observable of observable" I didn't found.

Thanks

**Comment by victimsnino** [comment]
Hi @klokane , you are welcome =)

Hmm, i think there is no any issue to **declare** such an type or variable, only possible issue is to **default construct** it (exactly what your error is saying). 

```cpp
using custom_type = rpp::dynamic_observable<rpp::dynamic_observable<int>>; // OK

int main() {
    // custom_type observable1{}; // compile error

    // but OK
    custom_type observable2 = rpp::source::just(rpp::source::just(1));
}
```
https://rpp.godbolt.org/z/fsf9jPK51

Reason is... `dynamic_observable<dynamic_observable<int>> observable{}` should construct observable, but if no anything passed to constructor -> observable is empty. What should it do in case of subscribe call? for example ,rxcpp is nearly UB in this case ([default construction](https://github.com/ReactiveX/RxCpp/blob/main/Rx/v2/src/rxcpp/rx-observable.hpp#L69) is not initializing [shared_ptr](https://github.com/ReactiveX/RxCpp/blob/main/Rx/v2/src/rxcpp/rx-observable.hpp#L46) and then is [not checking it](https://github.com/ReactiveX/RxCpp/blob/main/Rx/v2/src/rxcpp/rx-observable.hpp#L82).)

In rpp it is impossible to do because any observable should be ready to use. So, in your case you can only:
1) initialize observable in place of declaration (so, prevent default construction)
2) or make it "nullable" explicitly if it is required in your case, for example `std::optional<observable<observable<int>>>`

If this explanation is not solving your issue, please, provide a bit more context or code examples =)

**Comment by klokane** [comment]
Hi, thank you for really fast reaction. I'm preparing some examples, and one of them is implementation of "autocomplete" based on `switch_on_next()`. 

Relevant part is there.

```
using Response = std::vector<std::string>;

Response continents{ "africa","antarctica","asia","australia","europe","north america","south america" };

std::string input; // connected to GUI input box
std::vector<std::string> entries{}; // connected to GUI - rendering suggestions

// there I'm using subject, but I would like to replace it by
//rpp::dynamic_observable<rpp::dynamic_observable<Response>>
auto suggestions = rpp::subjects::behavior_subject<rpp::dynamic_observable<Response>>{ rpp::source::just(continents) };

// connected to (faked) web request
suggestions.get_observable()
  | rpp::ops::switch_on_next()
  | rpp::ops::subscribe([&](const auto& suggestions)
    {
      entries = suggestions;
     });

// faking web request (with delay) 
auto fakeRequest = [&](const std::string& keys){
  Response res;
  std::copy_if(continents.cbegin(), continents.cend(),
    std::back_inserter(res),
    [&](const auto& cont){ return cont.find(keys) != std::string::npos; });

  return rpp::source::just(res);
 };

// input from keyboard (via GUI)
 events
    | rpp::ops::filter([](const auto& ev){ return ev.is_character() || ev == Event::Backspace; })
    | rpp::ops::scan(std::string{}, [](std::string&& seed, const Event& ev)  {
        if (ev.is_character()) { seed += ev.character(); }
        else if (ev == Event::Backspace && !seed.empty()) { seed.pop_back(); }
        return std::move(seed);
      })
    | rpp::ops::subscribe([&](const auto& in) {
        // on input changed ask for new suggestions
        suggestions.get_observer().on_next(fakeRequest(in));
     });
```

Is it possible to implement it without `subject`?

**Comment by victimsnino** [comment]
Ok, a bit adapted your original code: https://rpp.godbolt.org/z/vEqM6YKsq. If it is valid output, then in this case you don't even need subject or dynamic_dynamic observable. If you want to keep it as is, then it is not possible to avoid subject: you want to subscribe and to emit to same variable at the same time: it is only subject (event with rxcpp there is no way to do it in other way). But if we rewrite it a bit, then it can be simplified a lot

https://rpp.godbolt.org/z/P4T8oTznv

in this case we are creating single observable and modifying input and etc. In case you want to split this observable and subscribe multiple observers, you can add `rpp::ops::publish() | rpp::ops::ref_count()`

**Comment by klokane** [comment]
Thank you, i didn't think of chain `map | switch_on_next` it looks fine.

My original idea was something like https://rpp.godbolt.org/z/ofvsYbzoz (see lines 15 and 51)

**Comment by victimsnino** [comment]
Yeah, i see. But it is incorrect idea at all due to you want to separate some observable as initial value. subscribe to it but what is then? you can't change this observable =) so, you need to build chain with union of two different observables
